import { useToast } from "@/hooks/use-toast";

interface DocumentData {
  title: string;
  summary: string;
  riskScore: string;
  totalClauses: number;
  riskyClauses: number;
  pages: number;
}

export const useDownloadSummary = () => {
  const { toast } = useToast();

  const downloadSummary = async (documentData: DocumentData) => {
    try {
      // Generate summary content
      const summaryContent = `
LEGAL DOCUMENT ANALYSIS SUMMARY
Generated by LegalSimplify

Document: ${documentData.title}
Date: ${new Date().toLocaleDateString()}

OVERVIEW
${documentData.summary}

DOCUMENT STATISTICS
• Total Pages: ${documentData.pages}
• Total Clauses: ${documentData.totalClauses}
• Risky Clauses: ${documentData.riskyClauses}
• Overall Risk Level: ${documentData.riskScore}

IMPORTANT NOTICE
This is explanatory guidance, not legal advice. Always consult with a qualified attorney for legal decisions.

Generated by LegalSimplify - AI Contract Explainer
      `.trim();

      // Create and download file
      const blob = new Blob([summaryContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `${documentData.title.replace(/[^a-zA-Z0-9]/g, '_')}_Summary.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);

      toast({
        title: "Summary downloaded",
        description: "The document summary has been saved to your downloads.",
      });
    } catch (error) {
      console.error("Download failed:", error);
      toast({
        title: "Download failed",
        description: "Could not download the summary. Please try again.",
        variant: "destructive",
      });
    }
  };

  return { downloadSummary };
};